### ISSUE TITLE
Scene graph implementation

### ISSUE THREAD

**Issue by bzm3r** [bzm3r/piet-dx12#2]
# Scene graph encoding implementation

A scene graph is very similar to an abstract syntax tree. The operator nodes are various transformations; we will focus on pure **translation** operations. [[1]](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/scene.20graphs/near/175124468)

Note that this does not mean that operations which are not translations are unsupported. Rather, it means that non-translation operations will be applied CPU side (i.e. they will not be represented as nodes in the scene graph, as they will be pre-applied to the terminal nodes of the graph). Currently, `piet-dx12` does not support any transformations apart from translations, which are applied CPU-side. Thus, we'll focus on shifting that work to the GPU using scene graphs.

The terminal nodes are various shapes: `piet-metal` provides circles, strokes, and fills. `piet-dx12` provides circles and characters. For now then, we will focus on **circles** and **characters**. 

A transformation in general can be applied to a number of nodes. So we'll have a data struct which captures this notion of grouping.

We can now enumerate the types of nodes we expect:

```

struct Character {
    glyph_id: u16,
    in_atlas_bbox: [u16; 4],
    in_scene_bbox: [u16; 4],
    color: [u8; 4],
}

struct Circle {
    in_scene_bbox: [u16; 4],
    color: [u8; 4],
}

struct Translation {
    delta_x: u16,
    delta_y: u16,
}

enum Transformation {
    Identity,
    Translation(Translation),
}

struct Group {
    transform: Transformation
    children: Vec<Box<Node>>,
}

enum Node {
    Character(Character),
    Circle(Circle),
    Group(Group),
}


```

Which in turn allows us to think more concretely about a `SceneGraph`:

```
struct SceneGraph {
    // allow empty graph
    root: Option<Group>,
}

// linear representation of tree structure for GPU consumption
struct ByteTreeStructure<Vec<u8>>;
// data for each transform/shape referenced by the tree structure
struct ByteData<Vec<u8>>

impl SceneGraph {
    pub fn build_from_context(context: piet::RenderContext) -> SceneGraph { 
    }
    
    pub fn encode_into_bytes(self) -> (ByteTreeStructure, ByteData) {
    }
    
}
```

`ByteData` will be a linear, indexed representation of the data in a scene graph (indentation provided for visual organization):
```
[
    index,
        data_size,
        data,
        ...,
        data,
    index,
        data_size,
        ...,
]
```

`ByteTreeStructure` will be a linear representation of the scene graph's tree structure referencing the indices in `ByteData`: 

```
[
    root_index, 
        num_children, 
            child_index,
            ... , 
            child_index, 
    root_index, 
        num_children, 
        child_index,
        ..., 
        child_index
    ...,
]
```

I still have to think about how the GPU will process the data in `ByteTreeStructure`/`ByteData`...

**Comment by raphlinus** [comment]
I responded on Zulip (https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/scene.20graphs), hopefully that helps answer some of these questions.
